name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.16.3]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: pwd; ls;
    - run: mkdir test
    - run: pwd
    - run: cd $GITHUB_WORKSPACE; ls;
    - run: cd $HOME; ls;
    - run: cd /home/runner/factory; ls;
    - run: cd /home/runner/perflog; ls;
    - run: cd /home/runner/runners; ls;
    - run: cd /home/runner/warmup; ls;
    - run: cd /home/runner/work; ls;
    - run: cd /home/runneradmin; ls;
    - run: cd /home/runner/work/_temp; ls;
    - run: ls
      
#       env:
#         CI: true
