name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [10.16.3]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: pwd
    - run: ls
    - run: cd /Users/runner; ls;
    - run: ls
      
      env:
        CI: true
