name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: macos

    strategy:
      matrix:
        node-version: [10.16.3]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: pwd
    - run: mkdir test
    - run: pwd
    - run: cd $GITHUB_WORKSPACE; ls;
    - run: cd $HOME; ls;
    - run: ls
      
#       env:
#         CI: true
